# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ailment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_diagnosed', models.DateTimeField(verbose_name='diagnosis date')),
                ('ailment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientprofiles.Ailment')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateTimeField(verbose_name='birthday')),
                ('last_seen', models.DateTimeField(verbose_name='last appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prescribed', models.DateTimeField(verbose_name='prescription date')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientprofiles.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendedMed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ailment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientprofiles.Ailment')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientprofiles.Medication')),
            ],
        ),
        migrations.AddField(
            model_name='prescription',
            name='recommended_med',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientprofiles.RecommendedMed'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientprofiles.Patient'),
        ),
    ]
