# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientprofiles', '0002_auto_20160823_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='ailment',
        ),
        migrations.RemoveField(
            model_name='diagnosis',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='recommended_med',
        ),
        migrations.RemoveField(
            model_name='recommendedmed',
            name='ailment',
        ),
        migrations.RemoveField(
            model_name='recommendedmed',
            name='medication',
        ),
        migrations.AddField(
            model_name='ailment',
            name='medication',
            field=models.ManyToManyField(to='patientprofiles.Medication'),
        ),
        migrations.AddField(
            model_name='patient',
            name='ailments',
            field=models.ManyToManyField(to='patientprofiles.Ailment'),
        ),
        migrations.DeleteModel(
            name='Diagnosis',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
        migrations.DeleteModel(
            name='RecommendedMed',
        ),
    ]
