# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientprofiles', '0003_auto_20160823_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAilment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_diagnosed', models.DateField(verbose_name='diagnosis date')),
            ],
        ),
        migrations.CreateModel(
            name='PatientAilmentMedication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prescribed', models.DateField(verbose_name='prescription date')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientprofiles.Medication')),
                ('patient_ailment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientprofiles.PatientAilment')),
            ],
        ),
        migrations.RemoveField(
            model_name='ailment',
            name='medication',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ailments',
        ),
        migrations.AddField(
            model_name='patientailment',
            name='ailment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientprofiles.Ailment'),
        ),
        migrations.AddField(
            model_name='patientailment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientprofiles.Patient'),
        ),
    ]
